import Recipes from "@/components/Recipes";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Recipes page",
  description: "Generated by create next app",
};
const ProductsPage = async () => {
  const data = await fetch("https://dummyjson.com/recipes", {cache: "force-cache"});
  const recipes = await data.json();

  return <div><Recipes data={recipes}/></div>;
};

export default ProductsPage;