import Hero from "@/components/Hero";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="container">
      <Hero />
     
    </div>
  );
}
