import Hero from "@/components/Hero";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="container">
      <h2>Next JS</h2>
      <p>Lorem ipsum dolor sit amet.</p>
      <Hero/>
    </div>
  );
}
