import Users from "@/components/Users";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "User page",
  description: "Generated by create next app",
};

const UsersPage = async () => {
  const data = await fetch("https://dummyjson.com/users", {cache: "force-cache"});
  const users = await data.json();

  return <div><Users data={users}/></div>;
};

export default UsersPage;