import Post from "@/components/Posts";
import { Metadata } from "next";
import React from "react";


export const metadata: Metadata = {
  title: "Products page",
  description: "Generated by create next app",
};
const PostsPage = async () => {
  const res = await fetch("https://dummyjson.com/posts", { cache: "force-cache" });
  const posts = await res.json();

  return <Post data={posts} />;
};

export default PostsPage;
