import Post from "@/components/Post";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Posts page",
    description: "Generated by create next app",
  };
const PostsPage = async () => {
  const data = await fetch("https://dummyjson.com/posts", {cache: "force-cache"});
  const posts = await data.json();

  return <div><Post data={posts}/></div>;
};

export default PostsPage;
