import Products from "@/components/Products";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Products page",
    description: "Generated by create next app",
  };
const ProductsPage = async () => {
  const data = await fetch("https://dummyjson.com/products", {cache: "force-cache"});
  const products = await data.json();

  return <div><Products data={products}/></div>;
};

export default ProductsPage;